# Generated by Django 5.1.4 on 2025-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("filters", models.TextField()),
                ("key_words", models.TextField()),
                ("photo_url", models.TextField()),
                ("rating", models.IntegerField()),
            ],
        ),
    ]
